services:
  backend:
    image: ghcr.io/magenta-mause/cosy-backend:sha-f8d6835
    container_name: cosy-backend
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${COSY_VOLUME_MOUNTS_PATH:-/opt/cosy/volume-mounts}:/workspace/dummy/cosy/volume-mounts
    group_add:
      - "988"
    environment:
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/cosydb
      - COSY_ENGINE_DOCKER_SOCKET_PATH=unix:///var/run/docker.sock
      - COSY_LOKI_URL=http://loki-nginx-proxy:80
      - COSY_LOKI_USER=${LOKI_USER}
      - COSY_LOKI_PASSWORD=${LOKI_PASSWORD}
      - COSY_INFLUX_URL=http://influx:8086
      - COSY_INFLUX_TOKEN=${COSY_INFLUXDB_ADMIN_TOKEN}
      - COSY_INFLUX_ORG=${COSY_INFLUXDB_ORG:-cosy-org}
      - COSY_INFLUX_BUCKET=${COSY_INFLUXDB_BUCKET:-cosy-bucket}
    depends_on:
      - database
      - loki
      - loki-nginx-proxy
      - influx
    networks:
      - cosy-network

  frontend:
    image: ghcr.io/magenta-mause/cosy-frontend:sha-28c1830
    ports:
      - "127.0.0.1:3000:80"
    depends_on:
      - backend
    networks:
      - cosy-network

  database:
    image: postgres:16
    environment:
      - POSTGRES_DB=cosydb
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - cosy-network

  loki:
    image: grafana/loki:2.9.4
    container_name: cosy-loki
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - loki-data:/loki
      - ./loki-config.yaml:/etc/loki/loki-config.yaml:ro
    networks:
      - cosy-network

  loki-nginx-proxy:
    image: nginx:1.25
    container_name: cosy-loki-nginx
    volumes:
      - ./loki-nginx.conf:/etc/nginx/nginx.conf:ro
      - ./htpasswd:/etc/nginx/htpasswd:ro
    networks:
      - cosy-network
    depends_on:
      - loki

  influx:
    image: influxdb:2.7-alpine
    container_name: cosy-influx
    volumes:
      - influx_data:/var/lib/influxdb2
      - influx_config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${COSY_INFLUXDB_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${COSY_INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${COSY_INFLUXDB_ORG:-cosy-org}
      DOCKER_INFLUXDB_INIT_BUCKET: ${COSY_INFLUXDB_BUCKET:-cosy-bucket}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${COSY_INFLUXDB_ADMIN_TOKEN}
    networks:
      - cosy-network

volumes:
  influx_data:
  influx_config:
  postgres-data:
  loki-data:

networks:
  cosy-network:

