services:
  backend:
    image: ghcr.io/magenta-mause/cosy-backend:sha-4f5a0ed
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - "988"
    environment:
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/cosydb
      - COSY_ENGINE_DOCKER_SOCKET_PATH=unix:///var/run/docker.sock
    depends_on:
      - database
    networks:
      - cosy-network

  frontend:
    image: ghcr.io/magenta-mause/cosy-frontend:sha-8f63848
    ports:
      - "127.0.0.1:3000:80"
    depends_on:
      - backend
    networks:
      - cosy-network

  database:
    image: postgres:16
    environment:
      - POSTGRES_DB=cosydb
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - cosy-network

volumes:
  postgres-data:

networks:
  cosy-network:

