global:
  storageClass: "local-path"
auth:
  existingSecret: "cosy-postgresql-credentials"
  username: cosyuser
  database: cosy
  secretKeys:
    userPasswordKey: "postgresql-password"
primary:
  persistence:
    enabled: true
    size: 5Gi
