apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-nginx-config
  namespace: cosy
data:
  nginx.conf: |
    events {}

    http {
      server {
        listen 80;

        location / {
          auth_basic "Loki";
          auth_basic_user_file /etc/nginx/htpasswd;

          proxy_pass http://loki:3100;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }
      }
    }

